import { Product } from './types';

export const products: Product[] = [
    {
        id: '1',
        name: 'Beaded Cocktail Dress',
        description: 'Stunning beaded cocktail dress with intricate African-inspired embellishments. Perfect for evening events and special occasions.',
        price: 185000,
        category: 'dresses',
        images: ['/beaded-cocktail-dress-african-glamour.jpg'],
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: ['Gold', 'Black'],
        inStock: true,
    },
    {
        id: '2',
        name: 'Luxurious Gold Wedding Gown',
        description: 'Breathtaking gold wedding gown with exquisite detailing. A statement piece for your special day.',
        price: 450000,
        category: 'bridal',
        images: ['/beautiful-african-bride-in-luxurious-gold-wedding-.jpg'],
        sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        colors: ['Gold', 'Champagne'],
        inStock: true,
    },
    {
        id: '3',
        name: 'Chiffon Boubou',
        description: 'Elegant chiffon boubou showcasing contemporary African fashion. Flowing and comfortable for any occasion.',
        price: 95000,
        category: 'separates',
        images: ['/chiffon-boubou-elegant-african-fashion.jpg'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        colors: ['Blue', 'Purple', 'Green'],
        inStock: true,
    },
    {
        id: '4',
        name: 'Luxurious Gold Evening Dress',
        description: 'Sophisticated gold evening dress with modern silhouette. Perfect for galas and upscale events.',
        price: 220000,
        category: 'gowns',
        images: ['/elegant-african-woman-in-luxurious-gold-dress-fash.jpg'],
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: ['Gold', 'Silver'],
        inStock: true,
    },
    {
        id: '5',
        name: 'Red Couture Gown',
        description: 'Show-stopping red couture gown with dramatic design. Runway-ready elegance for the modern woman.',
        price: 275000,
        category: 'gowns',
        images: ['/elegant-african-woman-in-red-couture-gown-runway-f.jpg'],
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: ['Red', 'Burgundy'],
        inStock: true,
    },
    {
        id: '6',
        name: 'Red Velvet Evening Gown',
        description: 'Timeless red velvet evening gown with luxurious fabric and impeccable tailoring.',
        price: 195000,
        category: 'gowns',
        images: ['/elegant-red-velvet-evening-gown-african-fashion.jpg'],
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Red', 'Wine'],
        inStock: true,
    },
    {
        id: '7',
        name: 'Gold Embroidered Kaftan',
        description: 'Regal gold embroidered kaftan celebrating Nigerian fashion heritage with contemporary flair.',
        price: 165000,
        category: 'separates',
        images: ['/gold-embroidered-kaftan-nigerian-fashion.jpg'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        colors: ['Gold', 'Cream', 'White'],
        inStock: true,
    },
    {
        id: '8',
        name: 'Lace Aso-Oke Ensemble',
        description: 'Traditional lace and aso-oke ensemble with modern styling. A celebration of Nigerian culture.',
        price: 145000,
        category: 'separates',
        images: ['/lace-aso-oke-traditional-nigerian-fashion.jpg'],
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Coral', 'Peach', 'Gold'],
        inStock: true,
    },
    {
        id: '9',
        name: 'Sequin Mermaid Gown',
        description: 'Glamorous sequin mermaid gown that captures the essence of Nigerian luxury fashion.',
        price: 285000,
        category: 'gowns',
        images: ['/sequin-mermaid-gown-nigerian-glamour-fashion.jpg'],
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: ['Gold', 'Silver', 'Rose Gold'],
        inStock: true,
    },
    {
        id: '10',
        name: 'Silk Wrap Dress',
        description: 'Versatile silk wrap dress with elegant draping. Perfect for both day and evening wear.',
        price: 125000,
        category: 'dresses',
        images: ['/silk-wrap-dress-african-woman-fashion.jpg'],
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: ['Navy', 'Black', 'Emerald'],
        inStock: true,
    },
    {
        id: '11',
        name: 'Contemporary Chic Outfit',
        description: 'Stylish contemporary outfit blending African aesthetics with modern design.',
        price: 155000,
        category: 'separates',
        images: ['/stylish-african-woman-in-chic-contemporary-outfit-.jpg'],
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Multi', 'Black', 'White'],
        inStock: true,
    },
    {
        id: '12',
        name: 'Royal Ankara Ensemble',
        description: 'Bold royal ankara ensemble with vibrant African prints and impeccable tailoring.',
        price: 135000,
        category: 'separates',
        images: ['/royal-ankara-ensemble-african-print-fashion.jpg'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        colors: ['Multi', 'Blue', 'Red'],
        inStock: true,
    },
];

export const categories = [
    { id: 'all', name: 'All Products', count: products.length },
    { id: 'dresses', name: 'Dresses', count: products.filter(p => p.category === 'dresses').length },
    { id: 'gowns', name: 'Gowns', count: products.filter(p => p.category === 'gowns').length },
    { id: 'separates', name: 'Separates', count: products.filter(p => p.category === 'separates').length },
    { id: 'bridal', name: 'Bridal', count: products.filter(p => p.category === 'bridal').length },
];
